/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RTBMS;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ricks
 */
public class A4_Admin_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Adminmenu3
     */
    public A4_Admin_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        showtrain_btn = new javax.swing.JButton();
        updatetriain_btn = new javax.swing.JButton();
        deletetrain_btn = new javax.swing.JButton();
        addtrian_btn = new javax.swing.JButton();
        SHOW_RESERVATION_BTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        exit_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        showalluser_btn = new javax.swing.JButton();
        update_PROTAL_BTN = new javax.swing.JButton();
        delete_register_user_btn = new javax.swing.JButton();
        DELETE_RESERVE_TICKET = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        showtrain_btn.setBackground(new java.awt.Color(51, 102, 0));
        showtrain_btn.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        showtrain_btn.setForeground(new java.awt.Color(255, 255, 255));
        showtrain_btn.setText("SHOW ALL TRAIN");
        showtrain_btn.setBorderPainted(false);
        showtrain_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showtrain_btnActionPerformed(evt);
            }
        });

        updatetriain_btn.setBackground(new java.awt.Color(153, 0, 153));
        updatetriain_btn.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        updatetriain_btn.setForeground(new java.awt.Color(255, 255, 255));
        updatetriain_btn.setText("UPDATE TRAIN");
        updatetriain_btn.setBorderPainted(false);
        updatetriain_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatetriain_btnActionPerformed(evt);
            }
        });

        deletetrain_btn.setBackground(new java.awt.Color(255, 51, 0));
        deletetrain_btn.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        deletetrain_btn.setForeground(new java.awt.Color(255, 255, 255));
        deletetrain_btn.setText("DELETE TRAIN");
        deletetrain_btn.setBorderPainted(false);
        deletetrain_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletetrain_btnActionPerformed(evt);
            }
        });

        addtrian_btn.setBackground(new java.awt.Color(51, 51, 255));
        addtrian_btn.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        addtrian_btn.setForeground(new java.awt.Color(255, 255, 255));
        addtrian_btn.setText("ADD TRAIN ");
        addtrian_btn.setBorderPainted(false);
        addtrian_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtrian_btnActionPerformed(evt);
            }
        });

        SHOW_RESERVATION_BTN.setBackground(new java.awt.Color(102, 0, 102));
        SHOW_RESERVATION_BTN.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        SHOW_RESERVATION_BTN.setForeground(new java.awt.Color(255, 255, 255));
        SHOW_RESERVATION_BTN.setText("SHOW RESERVATION");
        SHOW_RESERVATION_BTN.setBorderPainted(false);
        SHOW_RESERVATION_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOW_RESERVATION_BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(SHOW_RESERVATION_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatetriain_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addtrian_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(deletetrain_btn))
                    .addComponent(showtrain_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addtrian_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletetrain_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(updatetriain_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(showtrain_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(SHOW_RESERVATION_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 540));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        exit_btn.setBackground(new java.awt.Color(255, 0, 0));
        exit_btn.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        exit_btn.setForeground(new java.awt.Color(255, 255, 255));
        exit_btn.setText("EXIT");
        exit_btn.setBorderPainted(false);
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });

        logout_btn.setBackground(new java.awt.Color(255, 0, 0));
        logout_btn.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(255, 255, 255));
        logout_btn.setText("LOGOUT");
        logout_btn.setBorderPainted(false);
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });

        showalluser_btn.setBackground(new java.awt.Color(153, 0, 102));
        showalluser_btn.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        showalluser_btn.setForeground(new java.awt.Color(255, 255, 255));
        showalluser_btn.setText("SHOW ALL REGISTER USER");
        showalluser_btn.setBorderPainted(false);
        showalluser_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showalluser_btnActionPerformed(evt);
            }
        });

        update_PROTAL_BTN.setBackground(new java.awt.Color(0, 153, 51));
        update_PROTAL_BTN.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        update_PROTAL_BTN.setForeground(new java.awt.Color(255, 255, 255));
        update_PROTAL_BTN.setText("UPDATE PORTAL");
        update_PROTAL_BTN.setBorderPainted(false);
        update_PROTAL_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_PROTAL_BTNActionPerformed(evt);
            }
        });

        delete_register_user_btn.setBackground(new java.awt.Color(204, 51, 0));
        delete_register_user_btn.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        delete_register_user_btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_register_user_btn.setText("DELETE REGISTER USER");
        delete_register_user_btn.setBorderPainted(false);
        delete_register_user_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_register_user_btnActionPerformed(evt);
            }
        });

        DELETE_RESERVE_TICKET.setBackground(new java.awt.Color(204, 153, 0));
        DELETE_RESERVE_TICKET.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        DELETE_RESERVE_TICKET.setForeground(new java.awt.Color(255, 255, 255));
        DELETE_RESERVE_TICKET.setText("DELETE RESERVE TICKET");
        DELETE_RESERVE_TICKET.setBorderPainted(false);
        DELETE_RESERVE_TICKET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETE_RESERVE_TICKETActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 494, Short.MAX_VALUE)
                .addComponent(exit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DELETE_RESERVE_TICKET, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(update_PROTAL_BTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showalluser_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delete_register_user_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(exit_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(showalluser_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(delete_register_user_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(DELETE_RESERVE_TICKET, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(update_PROTAL_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 580, -1));

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rms all image/Admin_logo.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN PORTAL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel2)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 470, 450));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 45)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome To RTBMS Admin Portal");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(416, 416, 416)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(508, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel3)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, -1, -1));

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 480, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
         JFrame jf = new JFrame();
         int a = JOptionPane.showConfirmDialog(jf,"Do you really want to Logout from admin Protal","Select",JOptionPane.YES_NO_OPTION);
         if(a==0)
         {
            JOptionPane.showMessageDialog(jf,"Sucessfully Logout from Admin Protal");
            this.hide();
            A3_Admin_Login al3 = new A3_Admin_Login();
            al3.setVisible(true);
         }
         else{
            JOptionPane.showMessageDialog(jf,"Okay Stay Admin Protal!");
         }  
    }//GEN-LAST:event_logout_btnActionPerformed

    private void addtrian_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtrian_btnActionPerformed
        // TODO add your handling code here:
        this.hide();
        new A5_Addtrain_Portal().setVisible(true);
    }//GEN-LAST:event_addtrian_btnActionPerformed

    private void showtrain_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showtrain_btnActionPerformed
        // TODO add your handling code here:
        this.hide();
        new A8_Show_All_Train_Portal().setVisible(true);
    }//GEN-LAST:event_showtrain_btnActionPerformed

    private void update_PROTAL_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_PROTAL_BTNActionPerformed
        // TODO add your handling code here:
        this.hide();
        new B2_Update_Notification_All_Role().setVisible(true);
    }//GEN-LAST:event_update_PROTAL_BTNActionPerformed

    private void deletetrain_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletetrain_btnActionPerformed
        // TODO add your handling code here:
        this.hide();
        new A6_Deletetrain_Portal().setVisible(true);
    }//GEN-LAST:event_deletetrain_btnActionPerformed

    private void showalluser_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showalluser_btnActionPerformed
        // TODO add your handling code here:
        this.hide();
        new B1_Show_All_Register_User().setVisible(true);
    }//GEN-LAST:event_showalluser_btnActionPerformed

    private void updatetriain_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatetriain_btnActionPerformed
        // TODO add your handling code here:
        this.hide();
        new A7_Updatetrain_Portal().setVisible(true);
    }//GEN-LAST:event_updatetriain_btnActionPerformed

    private void delete_register_user_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_register_user_btnActionPerformed
        // TODO add your handling code here:
        this.hide();
        new A9_Delete_Register_User().setVisible(true);
        
    }//GEN-LAST:event_delete_register_user_btnActionPerformed

    private void SHOW_RESERVATION_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOW_RESERVATION_BTNActionPerformed
        // TODO add your handling code here:
        this.hide();
        new A99_show_all_reservation_ticket().setVisible(true);
    }//GEN-LAST:event_SHOW_RESERVATION_BTNActionPerformed

    private void DELETE_RESERVE_TICKETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETE_RESERVE_TICKETActionPerformed
        // TODO add your handling code here:
        this.hide();
        new A991_delete_reserve_ticket().setVisible(true);
    }//GEN-LAST:event_DELETE_RESERVE_TICKETActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A4_Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A4_Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A4_Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A4_Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A4_Admin_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DELETE_RESERVE_TICKET;
    private javax.swing.JButton SHOW_RESERVATION_BTN;
    private javax.swing.JButton addtrian_btn;
    private javax.swing.JButton delete_register_user_btn;
    private javax.swing.JButton deletetrain_btn;
    private javax.swing.JButton exit_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton showalluser_btn;
    private javax.swing.JButton showtrain_btn;
    private javax.swing.JButton update_PROTAL_BTN;
    private javax.swing.JButton updatetriain_btn;
    // End of variables declaration//GEN-END:variables
}
